export const BLOGPOST_CREATE_REQUEST = 'BLOGPOST_CREATE_REQUEST';
export const BLOGPOST_CREATE_SUCCESS = 'BLOGPOST_CREATE_SUCCESS';
export const BLOGPOST_CREATE_FAIL = 'BLOGPOST_CREATE_FAIL';
export const BLOGPOST_CREATE_RESET = 'BLOGPOST_CREATE_RESET';