export const BLOGPOST_CREATE_REQUEST = 'BLOGPOST_CREATE_REQUEST';
export const BLOGPOST_CREATE_SUCCESS = 'BLOGPOST_CREATE_SUCCESS';
export const BLOGPOST_CREATE_FAIL = 'BLOGPOST_CREATE_FAIL';
export const BLOGPOST_CREATE_RESET = 'BLOGPOST_CREATE_RESET';

export const BLOGPOST_LIST_REQUEST = 'BLOGPOST_LIST_REQUEST';
export const BLOGPOST_LIST_SUCCESS = 'BLOGPOST_LIST_SUCCESS';
export const BLOGPOST_LIST_FAIL = 'BLOGPOST_LIST_FAIL';

export const BLOGPOST_DETAILS_REQUEST = 'BLOGPOST_DETAILS_REQUEST';
export const BLOGPOST_DETAILS_SUCCESS = 'BLOGPOST_DETAILS_SUCCESS';
export const BLOGPOST_DETAILS_FAIL = 'BLOGPOST_DETAILS_FAIL';

export const BLOGPOST_LIST_BY_AUTHOR_REQUEST = 'BLOGPOST_LIST_BY_AUTHOR_REQUEST';
export const BLOGPOST_LIST_BY_AUTHOR_SUCCESS = 'BLOGPOST_LIST_BY_AUTHOR_SUCCESS';
export const BLOGPOST_LIST_BY_AUTHOR_FAIL = 'BLOGPOST_LIST_BY_AUTHOR_FAIL';

export const BLOGPOST_DELETE_REQUEST = 'BLOGPOST_DELETE_REQUEST';
export const BLOGPOST_DELETE_SUCCESS = 'BLOGPOST_DELETE_SUCCESS';
export const BLOGPOST_DELETE_FAIL = 'BLOGPOST_DELETE_FAIL';

export const BLOGPOST_UPDATE_REQUEST = 'BLOGPOST_UPDATE_REQUEST';
export const BLOGPOST_UPDATE_SUCCESS = 'BLOGPOST_UPDATE_SUCCESS';
export const BLOGPOST_UPDATE_FAIL = 'BLOGPOST_UPDATE_FAIL';
export const BLOGPOST_UPDATE_RESET = 'BLOGPOST_UPDATE_RESET';